#
# Copyright (C) 2021 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]

build:
  quality:
    filter:
      owner: vaticle
      branch: master
    dependency-analysis:
      image: vaticle-ubuntu-20.04
      command: |
        bazel run @vaticle_dependencies//factory/analysis:dependency-analysis
  correctness:
    build:
      image: vaticle-ubuntu-20.04
      command: |
        bazel build //... --test_output=errors
        bazel run @vaticle_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)')
    build-dependency:
      image: vaticle-ubuntu-20.04
      command: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @vaticle_dependencies//tool/unuseddeps:unused-deps -- list
#    TODO: enable this
#    deploy-rust-snapshot:
#      image: vaticle-ubuntu-20.04
#      dependencies: [build, build-dependency]
#      command: |
#        export DEPLOY_CRATE_TOKEN=$REPO_CRATES_TOKEN
#        bazel run --define version=$(cat VERSION) //grammar/rust:deploy-crate -- snapshot
    deploy-maven-snapshot:
      filter:
        owner: vaticle
        branch: master
      image: vaticle-ubuntu-20.04
      dependencies: [build, build-dependency]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_VATICLE_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_VATICLE_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //grammar/java:deploy-maven -- snapshot
    deploy-pip-snapshot:
      filter:
        owner: vaticle
        branch: master
      image: vaticle-ubuntu-20.04
      dependencies: [ build, build-dependency ]
      command: |
        export DEPLOY_PIP_USERNAME=$REPO_VATICLE_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_VATICLE_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //grammar/python:deploy-pip -- snapshot

release:
  filter:
    owner: vaticle
    branch: master
  deployment:
    deploy-github:
      image: vaticle-ubuntu-20.04
      command: |
        pyenv install -s 3.6.10
        pyenv global 3.6.10 system
        pip3 install certifi
        export CREATE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @vaticle_dependencies//tool/release/createnotes:bin -- $GRABL_OWNER $GRABL_REPO $GRABL_COMMIT $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
#    TODO: enable this
#    deploy-rust-release:
#      image: vaticle-ubuntu-20.04
#      dependencies: [ deploy-github ]
#      command: |
#        export DEPLOY_CRATE_TOKEN=$REPO_CRATES_TOKEN
#        bazel run --define version=$(cat VERSION) //grammar/rust:deploy-crate -- release
    deploy-maven-release:
      image: vaticle-ubuntu-20.04
      dependencies: [deploy-github]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_VATICLE_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_VATICLE_PASSWORD
        bazel run --define version=$(cat VERSION) //grammar/java:deploy-maven -- release
    deploy-pip-release:
      image: vaticle-ubuntu-20.04
      dependencies: [ deploy-github ]
      command: |
        export DEPLOY_PIP_USERNAME=$REPO_PYPI_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_PYPI_PASSWORD
        bazel run --define version=$(cat VERSION) //grammar/python:deploy-pip -- release
