#
# Copyright (C) 2021 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    typedb-common: [build, release]
    typedb-behaviour: [build]

build:
  quality:
    filter:
      owner: vaticle
      branch: master
    build-analysis:
      image: vaticle-ubuntu-20.04
      command: |
        SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
          bazel run @vaticle_dependencies//tool/sonarcloud:code-analysis -- \
          --project-key vaticle_typeql --branch=$GRABL_BRANCH --commit-id=$GRABL_COMMIT
    dependency-analysis:
      image: vaticle-ubuntu-20.04
      command: |
        bazel run @vaticle_dependencies//factory/analysis:dependency-analysis
  correctness:
    build:
      image: vaticle-ubuntu-20.04
      command: |
        bazel build //... --test_output=errors
        bazel run @vaticle_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)')
    build-dependency:
      image: vaticle-ubuntu-20.04
      command: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @vaticle_dependencies//tool/unuseddeps:unused-deps -- list
    test-typeql-java:
      image: vaticle-ubuntu-20.04
      command: |
        bazel test //java/... --test_output=errors
    deploy-maven-snapshot:
      filter:
        owner: vaticle
        branch: master
      image: vaticle-ubuntu-20.04
      dependencies: [build, build-dependency, test-typeql-java]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_VATICLE_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_VATICLE_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //grammar:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/common:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/pattern:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/query:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/parser:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java:deploy-maven -- snapshot
    test-deployment-maven:
      filter:
        owner: vaticle
        branch: master
      image: vaticle-ubuntu-20.04
      dependencies: [deploy-maven-snapshot]
      command: |
        sed -i -e "s/TYPEQL_LANG_VERSION_MARKER/$GRABL_COMMIT/g" java/test/deployment/pom.xml
        cd java/test/deployment/ && mvn test

release:
  filter:
    owner: vaticle
    branch: master
  validation:
    validate-dependencies:
      image: vaticle-ubuntu-20.04
      command: bazel test //:release-validate-deps --test_output=streamed
  deployment:
    deploy-github:
      image: vaticle-ubuntu-20.04
      command: |
        pyenv install -s 3.6.10
        pyenv global 3.6.10 system
        pip3 install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @vaticle_dependencies//tool/release:create-notes -- typeql $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-maven-release:
      image: vaticle-ubuntu-20.04
      dependencies: [deploy-github]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_VATICLE_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_VATICLE_PASSWORD
        bazel run --define version=$(cat VERSION) //grammar:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/common:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/pattern:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/query:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/parser:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java:deploy-maven -- release
