build:
  quality:
    job:
      build-analysis:
        machine: graknlabs-ubuntu-20.04
        script: |
          SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
            bazel run @graknlabs_dependencies//tool/sonarcloud:code-analysis -- \
            --project-key graknlabs_graql --branch=$GRABL_BRANCH --commit-id=$GRABL_COMMIT
  correctness:
    jobs:
      build:
        machine: graknlabs-ubuntu-20.04
        script: |
          bazel build --config=rbe //... --test_output=errors
          bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
          bazel test --config=rbe $(bazel query 'kind(checkstyle_test, //...)')
      build-dependency:
        machine: graknlabs-ubuntu-20.04
        script: |
          dependencies/maven/update.sh
          git diff --exit-code dependencies/maven/artifacts.snapshot
          bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
      test-graql-java:
        machine: graknlabs-ubuntu-20.04
        script: |
          bazel test --config=rbe //java/... --test_output=errors
      deploy-maven-snapshot:
        machine: graknlabs-ubuntu-20.04
        script: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //grammar:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/common:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/pattern:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/query:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java/parser:deploy-maven -- snapshot
          bazel run --define version=$(git rev-parse HEAD) //java:deploy-maven -- snapshot
      test-deployment-maven:
        machine: graknlabs-ubuntu-20.04
        script: |
          sudo apt-get update
          sudo apt-get -y install maven
          sed -i -e "s/GRAQL_LANG_VERSION_MARKER/$GRABL_COMMIT/g" java/test/deployment/pom.xml
          cd java/test/deployment/ && mvn test
    execution:
      - build
      - build-dependency
      - test-graql-java
      - deploy-maven-snapshot:
          depends: [build, build-dependency, test-graql-java]
      - test-deployment-maven:
          depends: [deploy-maven-snapshot]

release:
  validation:
    job:
      validate-dependencies:
        machine: graknlabs-ubuntu-20.04
        script: bazel test //:release-validate-deps --test_output=streamed
  deployment:
    jobs:
      deploy-github:
        machine: graknlabs-ubuntu-20.04
        script: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tool/release:create-notes -- graql $(cat VERSION) ./RELEASE_TEMPLATE.md
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
      deploy-maven-release:
        machine: graknlabs-ubuntu-20.04
        script: |
          export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //grammar:deploy-maven -- release
          bazel run --define version=$(cat VERSION) //java:deploy-maven -- release
    execution:
      - deploy-github
      - deploy-maven-release
