# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.


config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    typedb-behaviour: [build]

build:
  quality:
    filter:
      owner: typedb
      branch: [master, development]
    dependency-analysis:
      image: vaticle-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//factory/analysis:dependency-analysis
  correctness:
    build:
      image: vaticle-ubuntu-22.04
      command: |
        bazel build //... --test_output=errors
        bazel run @typedb_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)')
        bazel test $(bazel query 'kind(rustfmt_test, //...)') --@rules_rust//:rustfmt.toml=//rust:rustfmt_config
    build-dependency:
      image: vaticle-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @typedb_dependencies//tool/unuseddeps:unused-deps -- list
    test-java:
      image: vaticle-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel test //java/common/... --test_output=errors
        bazel test //java/parser/... --test_output=errors
        bazel test //java/pattern/... --test_output=errors
        bazel test //java/query/... --test_output=errors
        bazel test //java/test/... --test_output=errors
    test-rust:
      image: vaticle-ubuntu-22.04
      command: |
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel test //rust:typeql_unit_tests --test_output=errors
        bazel test //rust/tests/behaviour:test_behaviour --test_output=errors
    deploy-crate-snapshot:
      filter:
        owner: typedb
        branch: [master, development]
      image: vaticle-ubuntu-22.04
      dependencies: [build, build-dependency, test-rust]
      command: |
        export DEPLOY_CRATE_TOKEN=$REPO_TYPEDB_CRATES_TOKEN
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel run --define version=$(git rev-parse HEAD) //rust:deploy_crate -- snapshot
    deploy-maven-snapshot:
      filter:
        owner: typedb
        branch: [master, development]
      image: vaticle-ubuntu-22.04
      dependencies: [build, build-dependency, test-java]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel run --define version=$(git rev-parse HEAD) //grammar/java:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/builder:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/common:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/pattern:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/query:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java/parser:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //java:deploy-maven -- snapshot
        bazel run --define version=$(git rev-parse HEAD) //common/java:deploy-maven -- snapshot
    deploy-pip-snapshot:
      filter:
        owner: typedb
        branch: [master, development]
      image: vaticle-ubuntu-20.04
      dependencies: [ build, build-dependency ]
      command: |
        export DEPLOY_PIP_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //grammar/python:deploy-pip -- snapshot
    test-deployment-maven:
      filter:
        owner: typedb
        branch: [master, development]
      image: vaticle-ubuntu-22.04
      dependencies: [deploy-maven-snapshot]
      command: |
        sed -i -e "s/TYPEQL_LANG_VERSION_MARKER/0.0.0-$FACTORY_COMMIT/g" java/test/deployment/pom.xml
        cd java/test/deployment/ && mvn test
    sync-dependencies:
      image: vaticle-ubuntu-22.04
      filter:
        owner: typedb
        branch: [master, development]
      dependencies:
        - build
        - build-dependency
        - test-java
        - test-rust
        - deploy-crate-snapshot
        - deploy-maven-snapshot
        - deploy-pip-snapshot
        - test-deployment-maven
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @typedb_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@${FACTORY_COMMIT}

release:
  filter:
    owner: typedb
    branch: master
  validation:
    validate-release-notes:
      image: vaticle-ubuntu-22.04
      command: |
        export NOTES_VALIDATE_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @typedb_dependencies//tool/release/notes:validate --test_output=streamed -- $FACTORY_OWNER $FACTORY_REPO ./RELEASE_NOTES_LATEST.md
  deployment:
    deploy-github:
      image: vaticle-ubuntu-22.04
      command: |
        export PYENV_ROOT="/opt/pyenv"
        pyenv install 3.7.9
        pyenv global 3.7.9
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.7.9/lib/python3.7/site-packages/lsb_release.py
        python3 -m pip install certifi
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $FACTORY_COMMIT
    deploy-crate-release:
      image: vaticle-ubuntu-22.04
      dependencies: [ deploy-github ]
      command: |
        export DEPLOY_CRATE_TOKEN=$REPO_CRATES_TOKEN
        bazel run @typedb_dependencies//tool/bazelinstall:remote_cache_setup.sh
        bazel run --define version=$(cat VERSION) //rust:deploy_crate -- release
    deploy-maven-release:
      image: vaticle-ubuntu-22.04
      dependencies: [deploy-github]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_TYPEDB_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_TYPEDB_PASSWORD
        bazel run --define version=$(cat VERSION) //grammar/java:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/builder:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/common:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/pattern:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/query:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java/parser:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //java:deploy-maven -- release
        bazel run --define version=$(cat VERSION) //common/java:deploy-maven -- release
    deploy-pip-release:
      image: vaticle-ubuntu-20.04
      dependencies: [ deploy-github ]
      command: |
        export DEPLOY_PIP_USERNAME=$REPO_PYPI_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_PYPI_PASSWORD
        bazel run --define version=$(cat VERSION) //grammar/python:deploy-pip -- release
    sync-dependencies-release:
      image: vaticle-ubuntu-22.04
      filter:
        owner: typedb
        branch: [master, development]
      dependencies:
        - deploy-github
        - deploy-crate-release
        - deploy-maven-release
        - deploy-pip-release
      command: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @typedb_dependencies//tool/sync:dependencies -- --source ${FACTORY_REPO}@$(cat VERSION)
